// Copyright 2025 Maslennikova Mary

#ifndef FILM_LIBRARY_FILM_LIBRARY_FILM_LIBRARY_H
#define FILM_LIBRARY_FILM_LIBRARY_FILM_LIBRARY_H

class Film_library {
};
#endif  // FILM_LIBRARY_FILM_LIBRARY_FILM_LIBRARY_H
